config/routes.rb
Rails.application.routes.draw do
  
  
  devise_for :users
  root 'home#index'
  get 'vendor/dashboard', to: 'vendors#dashboard', as: :vendor_dashboard
  get 'potions', to: 'potions#index', as: :potions
  get 'potions/new', to: 'potions#new', as: :new_potion
  post 'potions', to: 'potions#create'
  get 'potions/:id', to: 'potions#show', as: :potion
  get 'potions/:id/edit', to: 'potions#edit', as: :edit_potion
  patch 'potions/:id', to: 'potions#update'
  put 'potions/:id', to: 'potions#update'
  delete 'potions/:id', to: 'potions#destroy'
  get 'potions/:id/vendor_show', to: 'potions#vendor_show', as: 'vendor_potion'

  get 'account', to: 'users#show'
  get 'orders', to: 'orders#index'
  
  get 'contests', to: 'contests#index', as: :contests
  post 'contests', to: 'contests#create'
  get 'contests/new', to: 'contests#new', as: :new_contest
  get 'contests/:id/edit', to: 'contests#edit', as: :edit_contest
  get 'contests/:contest_id/entries', to: 'contest_entries#index', as: :contest_entries
  get 'contests/:contest_id/entries/new', to: 'contest_entries#new', as: :new_contest_entry
  get 'contests/:contest_id/entries/:id/edit', to: 'contest_entries#edit', as: :edit_contest_entry
  patch 'contests/:contest_id/entries/:id/winner', to: 'contests#winner', as: :set_contest_winner
  delete 'contests/:contest_id/entries/:id/winner', to: 'contests#removewinner'
  get 'contests/:contest_id/entries/:id', to: 'contest_entries#show', as: :contest_entry
  patch 'contests/:contest_id/entries/:id', to: 'contest_entries#update'
  post 'contests/:contest_id/entries/:id/vote', to: 'contest_votes#create', as: :vote
  delete 'contests/:contest_id/entries/:id/vote', to: 'contest_votes#destroy'
  get 'contests/:id', to: 'contests#show', as: :contest
  patch 'contests/:id', to: 'contests#update'
  delete 'contests/:id', to: 'contests#destroy'
  get 'help', to: 'static_pages#help'

  get 'logout', to: 'sessions#destroy'


  get 'vendor/new', to: 'vendors#new', as: :new_vendor
  post 'vendor/new', to: 'vendors#create'


  #brewhub routes

  get 'brew_hub', to: 'brew_hub#index'
  get 'brew_hub/new', to: 'brew_hub#new', as: 'new_brew_hub_post'
  post 'brew_hub', to: 'brew_hub#create'
  get 'brew_hub/posts/:id', to: 'brew_hub#show', as: 'brew_hub_post'
  post 'brew_hub/posts/:id/reply', to: 'brew_hub#reply'
  get 'brew_hub/posts/:id/edit', to: 'brew_hub#edit', as: 'edit_brew_hub_post'
  patch 'brew_hub/posts/:id', to: 'brew_hub#update'
  get 'brew_hub/posts/:post_id/replies/new', to: 'brew_hub#new_reply', as: 'new_reply_brew_hub_post'
  delete 'brew_hub/posts/:id', to: 'brew_hub#destroy', as: 'delete_brew_hub_post'
  get 'brew_hub/posts/:id/view', to: 'brew_hub#view_post', as: 'view_brew_hub_post'

  get 'comment/:id', to: 'comments#edit', as: 'comment'
  patch 'comment/:id', to: 'comments#update'
  delete 'comment/:id', to: 'comments#destroy'
  post 'comment/:post_id', to: 'comments#create', as: 'new_comment'


  #cart routes

  resource :cart, only: [:show]
  post 'cart_items', to: 'cart_items#create'
  patch 'cart_items/:id', to: 'cart_items#update', as: 'update_cart_item'
  delete 'cart_items/:id', to: 'cart_items#destroy', as: 'delete_cart_item'
  get 'cart_items/:id', to: 'cart_items#show', as: 'cart_item'
  get 'cart_items/:id/edit', to: 'cart_items#edit', as: 'edit_cart_item'

  get 'help', to: 'static_pages#help'


  resources :orders

  resources :orders do
    member do
      patch :mark_as_shipped
      patch :cancel
      put :cancel_by_user
    end
  end

  resources :contests do
    resources :contest_entries, only: [:new, :create, :show]
  end

end

app/models/contest.rb
# == Schema Information
#
# Table name: contests
#
#  id         :bigint           not null, primary key
#  desc       :text
#  end_date   :datetime
#  title      :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  vendor_id  :bigint           not null
#  winner_id  :bigint
#
# Indexes
#
#  index_contests_on_vendor_id  (vendor_id)
#  index_contests_on_winner_id  (winner_id)
#
# Foreign Keys
#
#  fk_rails_...  (vendor_id => vendors.id)
#  fk_rails_...  (winner_id => contest_entries.id)
#
class Contest < ApplicationRecord
    belongs_to(
        :vendor,
        class_name:  'Vendor',
        foreign_key: 'vendor_id',
        inverse_of:  :contests
   )
   has_one_attached :image
   has_one(
    :winner,
    class_name:  'ContestEntry',
    foreign_key: 'id',
    inverse_of:  :contest_won
   )
   has_many :contest_entries
end

app/controllers/contests_controller.rb
class ContestsController < ApplicationController
  before_action :set_contest, only: %i[ show edit update destroy ]

  # GET /contests or /contests.json
  def index
    #TODO: only show non-ended contests
    @contests = Contest.all
  end

  # GET /contests/1 or /contests/1.json
  def show
    @contest = Contest.find(params[:id])
    @now = DateTime.now
    if @contest.winner_id
      @winner = ContestEntry.find(@contest.winner_id)
    end
    render :show
  end

  # GET /contests/new
  def new
    @contest = Contest.new
  end

  # GET /contests/1/edit
  def edit
    @contest = Contest.find(params[:id])
    render :edit
  end

  # POST /contests or /contests.json
  def create
    @contest = current_user.vendor.contests.build(params.require(:contest).permit(:title, :desc, :image, :end_date))
      if @contest.save
        flash[:success] = 'Contest was successfully updated.'
      redirect_to contest_path(@contest)
      else
        flash.now[:error] = 'Unable to update Contest.'
      render :edit, status: :unprocessable_entity
      end
  end

  # PATCH/PUT /contests/1 or /contests/1.json
  def update
    @contest = Contest.find(params[:id])
    if @contest.update(params.require(:contest).permit(:title, :desc, :image, :end_date))
      flash[:success] = 'Contest was successfully updated.'
      redirect_to contest_path(@contest)
    else
      flash.now[:error] = 'Unable to update Contest.'
      render :edit, status: :unprocessable_entity
    end
  end

  # DELETE /contests/1 or /contests/1.json
  def destroy
    @contest = Contest.find(params[:id])
    @contest.destroy
    flash[:success] = 'Contest was successfully destroyed.'
    redirect_to contests_url
  end

  def winner
    contest = Contest.find(params[:contest_id])
    entry = ContestEntry.find(params[:id])
    contest.winner_id = entry.id
    if contest.end_date > DateTime.now
      contest.end_date = DateTime.now
    end
    if contest.save
      flash[:success] = 'Contest winner was set.'
      redirect_to contest_path(contest)
    else
      flash.now[:error] = 'Unable to set contest winner.'
      redirect_to contest_path(contest)
    end
  end

  def removewinner
    contest = Contest.find(params[:contest_id])
    contest.winner_id = nil
    if contest.save
      flash[:success] = 'Contest winner was removed.'
      redirect_to contest_path(contest)
    else
      flash.now[:error] = 'Unable to remove contest winner.'
      redirect_to contest_path(contest)
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_contest
      @contest = Contest.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def contest_params
      params.fetch(:contest, {})
    end
end

app/helpers/contests_helper.rb
module ContestsHelper
end

app/views/contests/_contest.html.erb
<div id="<%= dom_id contest %>">
</div>

app/views/contests/_form.html.erb
<%= form_with(model: contest) do |form| %>
  <% if contest.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(contest.errors.count, "error") %> prohibited this contest from being saved:</h2>

      <ul>
        <% contest.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/contests/edit.html.erb
<style>
  .edit-contest-form {
    font-family: 'Cormorant', serif;
    color: #301934;
    background-color: #fff5e5;
    padding: 20px;
    max-width: 600px;
    margin: auto;
    border-radius: 10px;
    box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);
  }

  .edit-contest-form h1 {
    text-align: center;
    color: #5D4037;
  }

  .edit-contest-form input, .edit-contest-form textarea {
    width: 100%;
    padding: 8px;
    margin-bottom: 10px;
    border: 1px solid #8e6e53;
    border-radius: 4px;
    background-color: #f4e3be;
  }

  .edit-contest-form .btn-primary {
    background-color: #7c3f2d;
    color: white;
    border: none;
    border-radius: 4px;
    padding: 10px 15px;
    font-weight: bold;
    display: block;
    width: 100%;
  }

  .edit-contest-form .btn-primary:hover {
    background-color: darken(#7c3f2d, 10%);
  }

  .back-links {
    text-align: center;
    margin-top: 20px;
  }

  .back-links a {
    color: #7c3f2d;
    text-decoration: none;
    padding: 5px 10px;
    margin: 0 5px;
  }

  .back-links a:hover {
    text-decoration: underline;
  }
</style>

<div class="edit-contest-form">
  <h1>Edit Contest</h1>

  <%= bootstrap_form_with model: @contest, url: contest_path(@contest), method: :patch, data: { turbo: false } do |form| %>
    <%= form.text_field :title, label: 'Contest Title' %>
    <%= form.text_area :desc, rows: 16, label: 'Description' %>
    <%= form.file_field :image, label: 'Contest Image' %>
    <%= form.datetime_field :end_date, label: 'End Date' %>
    <%= form.submit 'Update Contest', class: 'btn btn-primary my-3' %>
  <% end %>

  <div class="back-links">
    <%= link_to "Show this contest", contest_path(@contest) %> |
    <%= link_to "Back to contests", contests_path %>
  </div>
</div>

app/views/contests/index.html.erb
<style>
  .contests-page {
    font-family: 'Cormorant', serif;
    color: #301934;
    background-color: #fff5e5;
  }

  .card {
    background: #f4e3be;
    border: 1px solid #8e6e53;
    border-radius: 10px;
    box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);
  }

  .card-body, .card-footer {
    background-color: transparent;
  }

  .card-title {
    color: #5D4037;
  }
    .card-img-container {
    width: 160px; /* Fixed width */
    height: 160px; /* Fixed height to make the image square */
    margin: 10px auto; /* Centering the image container */
    overflow: hidden; /* Hide parts of the image that overflow */
  }

  .card-img-top {
    width: 100%; /* Make the image take the full width of the container */
    height: auto; /* Adjust height automatically */
    display: block; /* Ensures the image is a block level element */
    object-fit: cover; /* Ensures the image covers the container */
    margin: auto; /* Center the image if it's not square */
  }


  .card-text, .text-body-secondary {
    color: #666;
  }

  .btn-primary, .btn-success {
    background-color: #7c3f2d;
    border-color: #5d2e1f;
    color: white;
  }

  .btn-primary:hover, .btn-success:hover {
    background-color: darken(#7c3f2d, 10%);
    border-color: darken(#5d2e1f, 10%);
  }

  .btn-sm {
    padding: 5px 10px;
    font-size: 0.875rem;
  }
.joined-contests-container {
    display: grid;
    grid-template-columns: repeat(auto-fill, minmax(300px, 1fr)); /* Adjust the minmax values as needed */
    grid-gap: 20px; /* Space between cards */
    padding: 20px;
  }

  .joined-contest-card {
    background: #f4e3be;
    border: 1px solid #8e6e53;
    border-radius: 10px;
    box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);
    padding: 10px;
    display: flex;
    flex-direction: column;
    justify-content: space-between;
  }

  .joined-contest-image {
    width: 100px; /* Fixed width */
    height: 100px; /* Fixed height */
    object-fit: cover;
    border-radius: 10px;
    margin: 0 auto 10px; /* Center the image with margin */
  }

  .contest-entry-details {
    text-align: center;
  }


  .joined-card-footer {
    display: flex;
    justify-content: space-between;
  }

  /* Adjusted hover colors for buttons */
  .btn-secondary:hover, .btn-primary:hover {
    background-color: #94785e; /* New hover color */
  }

  .contest-card-footer {
    display: flex;
    justify-content: space-between;
    align-items: center;
    padding-top: 10px;
  }

  .btn-footer {
    margin: 0; /* Reset margin for buttons */
    flex-grow: 0; /* Prevent buttons from stretching */
  }

  .btn-secondary, .btn-primary {
    /* Button styling */
    background-color: #7c3f2d;
    border-color: #5d2e1f;
    color: white;
    padding: 5px 10px;
    text-decoration: none;
    border-radius: 4px;
    font-size: 0.875rem;
    flex-grow: 0; /* Prevent buttons from stretching */
  }

  /* Adjusted hover colors for buttons */
  .btn-secondary:hover, .btn-primary:hover {
    background-color: #94785e; /* New hover color */
  }

  
</style>

<div class="contests-page">
  <p style="color: green"><%= notice %></p>

  <h1>Contests</h1>
  <div class="row row-cols-1 row-cols-md-4 g-4" id="contests">
    <% @contests.each do |contest| %>
      <div class="col">
        <div class="card h-100">
          <% if contest.image.attached? %>
            <div class="card-img-container">
              <%= image_tag contest.image, class: 'card-img-top' %>
            </div>
          <% end %>
          <div class="card-body">
            <h5 class="card-title"><%= contest.title %></h5>
            <p class="card-text"><%= contest.desc %></p>
          </div>
          <div class="card-footer">
            <small class="text-body-secondary">Ends: <%= contest.end_date %></small>
            
                <%= link_to 'View Contest', contest, class: 'btn btn-primary' %>
                <%= link_to 'View Entries', contest_entries_path(contest), class: 'btn btn-primary' %>
              
          </div>    
        </div>
      </div>
    <% end %>
  </div>
<br>
<% if user_signed_in? and current_user.vendor%>
  <div>
    <%= link_to "New contest", new_contest_path, class: 'btn btn-success btn-sm' %>
  </div>
<% end %>
<% if user_signed_in? %>
<h2>Joined Contests</h2>
  <div class="joined-contests-container">
    <% current_user.contest_entries.each do |entry| %>
      <% contest = entry.contest %>
      <div class="joined-contest-card">
        <div class="contest-entry-details">
          <% if entry.image.attached? %>
            <%= image_tag entry.image, class: 'joined-contest-image' %>
          <% end %>
          <h5 class="card-title"><%= contest.title %> - <%= entry.potion_name %></h5>
          <p class="card-text"><%= entry.description %></p>
        </div>
        <div class="contest-card-footer">
          <%= link_to 'View Your Submission', contest_contest_entry_path(contest, entry), class: 'btn btn-secondary btn-sm btn-footer' %>
          <%= link_to 'View Contest', contest, class: 'btn btn-secondary btn-sm btn-footer' %>
        </div>
      </div>
    <% end %>
  </div>
<% end %>

app/views/contests/new.html.erb
<style>
  .new-contest-form {
    font-family: 'Cormorant', serif;
    color: #301934;
    background-color: #fff5e5;
    padding: 20px;
    max-width: 600px;
    margin: auto;
    border-radius: 10px;
    box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);
  }

  .new-contest-form h1 {
    text-align: center;
    color: #5D4037;
  }

  .new-contest-form input, .new-contest-form textarea {
    width: 100%;
    padding: 8px;
    margin-bottom: 10px;
    border: 1px solid #8e6e53;
    border-radius: 4px;
    background-color: #f4e3be;
  }

  .new-contest-form .btn-primary {
    background-color: #7c3f2d;
    color: white;
    border: none;
    border-radius: 4px;
    padding: 10px 15px;
    font-weight: bold;
    display: block;
    width: 100%;
  }

  .new-contest-form .btn-primary:hover {
    background-color: darken(#7c3f2d, 10%);
  }

    .back-to-contests-link {
    display: inline-block;
    padding: 10px 15px;
    background-color: #94785e; /* Different color for the back link */
    color: white;
    border-radius: 4px;
    text-decoration: none;
    font-weight: bold;
    margin-top: 20px;
  }

  .back-to-contests-link:hover {
    background-color: #a17455; /* Darker shade on hover */
  }
</style>

<div class="new-contest-form">
  <h1>New Contest</h1>

  <%= bootstrap_form_with model: @contest, url: contests_path, method: :post, data: { turbo: false } do |form| %>
    <%= form.text_field :title, label: 'Contest Title' %>
    <%= form.text_area :desc, rows: 16, label: 'Description' %>
    <%= form.file_field :image, label: 'Contest Image' %>
    <%= form.datetime_field :end_date, label: 'End Date' %>
    <%= form.submit 'Create Contest', class: 'btn btn-primary my-3' %>
  <% end %>

  <div class="back-to-contests-link">
    <%= link_to "Back to contests", contests_path %>
  </div>
</div>

app/views/contests/show.html.erb
<style>
  .contest-show-page {
    font-family: 'Cormorant', serif;
    color: #301934;
    background-color: #fff5e5;
    max-width: 800px;
    margin: auto;
  }

  .contest-image {
    width: 100%; /* Full width of the container */
    max-width: 400px; /* Maximum width */
    height: auto; /* Maintain aspect ratio */
    display: block;
    margin: 20px auto; /* Centering the image */
  }

  .btn-primary, .btn-success, .btn-secondary, .btn-danger {
    background-color: #7c3f2d;
    border-color: #5d2e1f;
    color: white;
    padding: 10px 15px;
    border-radius: 4px;
    text-decoration: none;
    font-weight: bold;
  }

  .btn-primary:hover, .btn-success:hover, .btn-secondary:hover, .btn-danger:hover {
    background-color: darken(#7c3f2d, 10%);
  }

 .btn-group {
    display: flex;
    justify-content: space-around; /* Adjusts the positioning */
    margin-top: 20px;
  }

  .btn-group .btn {
    flex: 1; /* Allows buttons to share the available space */
    margin: 0 10px; /* Adds some space between buttons */
  }
</style>

<div class="contest-show-page">
  <p style="color: green"><%= notice %></p>

  <h1><%= @contest.title %></h1>

  <% if @contest.image.attached? %>
    <%= image_tag @contest.image, class: 'contest-image' %>
  <% end %>
  <p><%= @contest.desc %></p>
  <br>
  <% if @contest.winner_id %>
  <div>
  <h3>Winner: </h3>
    <table class="table table-image" style="color: black;">
		  <tbody>
        <tr>
            <td class="w-25">
                <% if @winner.image.attached? %>
                <%= image_tag @winner.image, class: "img-fluid img-thumbnail" %>
                <% end %>
            </td>
            <td>
            <h4><%= @winner.potion_name %></h4><br>
            <p><%= @winner.description %></p>
            <br>
            <% @num_votes =  @winner.contest_votes.length() %>
            <div id="vote-num"><%= @num_votes %> Vote<% if @num_votes > 1 or @num_votes == 0 %>s<% end %></div>
            <br>
            <div class="btn-group" role="group">
              
            </div>
            </td>
        </tr>
		  </tbody>
		</table>
  </div>
  <% end %>
  <br>
  <% if user_signed_in? and current_user.vendor and (current_user.vendor == @contest.vendor)%>
    <div class="btn-group" role="group">
      <%= link_to "Edit this contest", edit_contest_path(@contest), class: "btn btn-secondary" %>
      <%= button_to "Delete this contest", @contest, method: :delete, class: "btn btn-danger", id: "destroy-btn-groupd" %>
    </div>
  <% end %>
</div>


<div>
<% if user_signed_in? and @contest.end_date > @now  %>
    <%= link_to "Submit to this contest", new_contest_contest_entry_path(@contest), class: "btn btn-success" %>
<% end %>
<%= link_to "Back to contests", contests_path, class: "btn btn-success" %>
<%= link_to "View Entries", contest_entries_path(@contest), class: "btn btn-success" %>
</div>