config/routes.rb
Rails.application.routes.draw do
  
  
  devise_for :users
  root 'home#index'
  get 'vendor/dashboard', to: 'vendors#dashboard', as: :vendor_dashboard
  get 'potions', to: 'potions#index', as: :potions
  get 'potions/new', to: 'potions#new', as: :new_potion
  post 'potions', to: 'potions#create'
  get 'potions/:id', to: 'potions#show', as: :potion
  get 'potions/:id/edit', to: 'potions#edit', as: :edit_potion
  patch 'potions/:id', to: 'potions#update'
  put 'potions/:id', to: 'potions#update'
  delete 'potions/:id', to: 'potions#destroy'
  get 'potions/:id/vendor_show', to: 'potions#vendor_show', as: 'vendor_potion'

  get 'account', to: 'users#show'
  get 'orders', to: 'orders#index'
  
  get 'contests', to: 'contests#index', as: :contests
  post 'contests', to: 'contests#create'
  get 'contests/new', to: 'contests#new', as: :new_contest
  get 'contests/:id/edit', to: 'contests#edit', as: :edit_contest
  get 'contests/:contest_id/entries', to: 'contest_entries#index', as: :contest_entries
  get 'contests/:contest_id/entries/new', to: 'contest_entries#new', as: :new_contest_entry
  get 'contests/:contest_id/entries/:id/edit', to: 'contest_entries#edit', as: :edit_contest_entry
  patch 'contests/:contest_id/entries/:id/winner', to: 'contests#winner', as: :set_contest_winner
  delete 'contests/:contest_id/entries/:id/winner', to: 'contests#removewinner'
  get 'contests/:contest_id/entries/:id', to: 'contest_entries#show', as: :contest_entry
  patch 'contests/:contest_id/entries/:id', to: 'contest_entries#update'
  post 'contests/:contest_id/entries/:id/vote', to: 'contest_votes#create', as: :vote
  delete 'contests/:contest_id/entries/:id/vote', to: 'contest_votes#destroy'
  get 'contests/:id', to: 'contests#show', as: :contest
  patch 'contests/:id', to: 'contests#update'
  delete 'contests/:id', to: 'contests#destroy'
  get 'help', to: 'static_pages#help'

  get 'logout', to: 'sessions#destroy'


  get 'vendor/new', to: 'vendors#new', as: :new_vendor
  post 'vendor/new', to: 'vendors#create'


  #brewhub routes

  get 'brew_hub', to: 'brew_hub#index'
  get 'brew_hub/new', to: 'brew_hub#new', as: 'new_brew_hub_post'
  post 'brew_hub', to: 'brew_hub#create'
  get 'brew_hub/posts/:id', to: 'brew_hub#show', as: 'brew_hub_post'
  post 'brew_hub/posts/:id/reply', to: 'brew_hub#reply'
  get 'brew_hub/posts/:id/edit', to: 'brew_hub#edit', as: 'edit_brew_hub_post'
  patch 'brew_hub/posts/:id', to: 'brew_hub#update'
  get 'brew_hub/posts/:post_id/replies/new', to: 'brew_hub#new_reply', as: 'new_reply_brew_hub_post'
  delete 'brew_hub/posts/:id', to: 'brew_hub#destroy', as: 'delete_brew_hub_post'
  get 'brew_hub/posts/:id/view', to: 'brew_hub#view_post', as: 'view_brew_hub_post'

  get 'comment/:id', to: 'comments#edit', as: 'comment'
  patch 'comment/:id', to: 'comments#update'
  delete 'comment/:id', to: 'comments#destroy'
  post 'comment/:post_id', to: 'comments#create', as: 'new_comment'


  #cart routes

  resource :cart, only: [:show]
  post 'cart_items', to: 'cart_items#create'
  patch 'cart_items/:id', to: 'cart_items#update', as: 'update_cart_item'
  delete 'cart_items/:id', to: 'cart_items#destroy', as: 'delete_cart_item'
  get 'cart_items/:id', to: 'cart_items#show', as: 'cart_item'
  get 'cart_items/:id/edit', to: 'cart_items#edit', as: 'edit_cart_item'

  get 'help', to: 'static_pages#help'


  resources :orders

  resources :orders do
    member do
      patch :mark_as_shipped
      patch :cancel
      put :cancel_by_user
    end
  end

  resources :contests do
    resources :contest_entries, only: [:new, :create, :show]
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @posts = Post.limit(3)  # Adjust the number based on how many recent posts you want to display
    @contests = Contest.limit(3)  # Adjust for contests
    @random_potions = Potion.order("RANDOM()").limit(3)
    render :index
  end
  
  def show
    render :show
  end

  def image_number_for_category(category)
    image_ranges = {
      "Love" => 1..5,
      "Mind Control" => 6..10,
      "Strength" => 11..15,
      "Healing" => 16..20,
      "Invisibility" => 21..25
    }
  
    range = image_ranges[category]
    rand(range)
  end
  

end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
<div class="header-decoration">✨🔮✨</div>
<h1>Welcome to Hogwarts Potion Kart</h1>
<p>Your one-stop shop for all magical potion needs!</p>

<!-- Featured Potions Section -->
<h2>Featured Potions</h2>
<div class="featured-potions">
  <% @random_potions.each do |potion| %>
    <div class="potion-preview-card">
      <%= link_to potion_path(potion) do %>
        <% if potion.images.attached? %>
          <%= image_tag potion.images.first, class: 'potion-preview-image' %>
        <% else %>
          <%= image_tag 'default_potion_image.jpg', class: 'potion-preview-image' %>
        <% end %>
        <div class="potion-preview-details">
          <h3 class="potion-title"><%= potion.name %></h3>
          <p class="potion-effect"><%= truncate(potion.effect, length: 100) %></p>
          <p class="potion-price">Price: <%= number_to_currency(potion.price) %></p>
        </div>
      <% end %>
    </div>
  <% end %>
</div>

<!-- BrewHub Posts and Contests Sections -->
<div class="bottom-sections">
  <!-- Latest BrewHub Posts Section -->
  <div class="latest-posts">
    <h2>Latest BrewHub Posts</h2>
    <% @posts.each do |post| %>
      <div class="post-preview">
        <h3><%= post.title %></h3>
        <p><%= truncate(post.content, length: 100) %></p>
        <%= link_to 'Read More', brew_hub_post_path(post), class: 'btn btn-primary' %>
      </div>
    <% end %>
  </div>

  <!-- Upcoming Contest Section -->
  <div class="upcoming-contests">
    <h2>Upcoming Contest</h2>
    <% if @contests.any? %>
      <% contest = @contests.first %>
      <div class="contest-preview">
        <% if contest.image.attached? %>
          <%= image_tag contest.image, class: 'contest-image' %>
        <% end %>
        <h3><%= contest.title %></h3>
        <p><%= truncate(contest.desc, length: 100) %></p>
        <%= link_to 'View Contest', contest_path(contest), class: 'btn btn-secondary' %>
      </div>
    <% else %>
      <p>No upcoming contests.</p>
    <% end %>
  </div>
</div>

app/views/home/show.html.erb
<h1>Home Page</h1>

<p>
  Find me in app/views/home/show.html.erb
</p>