config/routes.rb
Rails.application.routes.draw do
  
  
  devise_for :users
  root 'home#index'
  get 'vendor/dashboard', to: 'vendors#dashboard', as: :vendor_dashboard
  get 'potions', to: 'potions#index', as: :potions
  get 'potions/new', to: 'potions#new', as: :new_potion
  post 'potions', to: 'potions#create'
  get 'potions/:id', to: 'potions#show', as: :potion
  get 'potions/:id/edit', to: 'potions#edit', as: :edit_potion
  patch 'potions/:id', to: 'potions#update'
  put 'potions/:id', to: 'potions#update'
  delete 'potions/:id', to: 'potions#destroy'
  get 'potions/:id/vendor_show', to: 'potions#vendor_show', as: 'vendor_potion'

  get 'account', to: 'users#show'
  get 'orders', to: 'orders#index'
  
  get 'contests', to: 'contests#index', as: :contests
  post 'contests', to: 'contests#create'
  get 'contests/new', to: 'contests#new', as: :new_contest
  get 'contests/:id/edit', to: 'contests#edit', as: :edit_contest
  get 'contests/:contest_id/entries', to: 'contest_entries#index', as: :contest_entries
  get 'contests/:contest_id/entries/new', to: 'contest_entries#new', as: :new_contest_entry
  get 'contests/:contest_id/entries/:id/edit', to: 'contest_entries#edit', as: :edit_contest_entry
  patch 'contests/:contest_id/entries/:id/winner', to: 'contests#winner', as: :set_contest_winner
  delete 'contests/:contest_id/entries/:id/winner', to: 'contests#removewinner'
  get 'contests/:contest_id/entries/:id', to: 'contest_entries#show', as: :contest_entry
  patch 'contests/:contest_id/entries/:id', to: 'contest_entries#update'
  post 'contests/:contest_id/entries/:id/vote', to: 'contest_votes#create', as: :vote
  delete 'contests/:contest_id/entries/:id/vote', to: 'contest_votes#destroy'
  get 'contests/:id', to: 'contests#show', as: :contest
  patch 'contests/:id', to: 'contests#update'
  delete 'contests/:id', to: 'contests#destroy'
  get 'help', to: 'static_pages#help'

  get 'logout', to: 'sessions#destroy'


  get 'vendor/new', to: 'vendors#new', as: :new_vendor
  post 'vendor/new', to: 'vendors#create'


  #brewhub routes

  get 'brew_hub', to: 'brew_hub#index'
  get 'brew_hub/new', to: 'brew_hub#new', as: 'new_brew_hub_post'
  post 'brew_hub', to: 'brew_hub#create'
  get 'brew_hub/posts/:id', to: 'brew_hub#show', as: 'brew_hub_post'
  post 'brew_hub/posts/:id/reply', to: 'brew_hub#reply'
  get 'brew_hub/posts/:id/edit', to: 'brew_hub#edit', as: 'edit_brew_hub_post'
  patch 'brew_hub/posts/:id', to: 'brew_hub#update'
  get 'brew_hub/posts/:post_id/replies/new', to: 'brew_hub#new_reply', as: 'new_reply_brew_hub_post'
  delete 'brew_hub/posts/:id', to: 'brew_hub#destroy', as: 'delete_brew_hub_post'
  get 'brew_hub/posts/:id/view', to: 'brew_hub#view_post', as: 'view_brew_hub_post'

  get 'comment/:id', to: 'comments#edit', as: 'comment'
  patch 'comment/:id', to: 'comments#update'
  delete 'comment/:id', to: 'comments#destroy'
  post 'comment/:post_id', to: 'comments#create', as: 'new_comment'


  #cart routes

  resource :cart, only: [:show]
  post 'cart_items', to: 'cart_items#create'
  patch 'cart_items/:id', to: 'cart_items#update', as: 'update_cart_item'
  delete 'cart_items/:id', to: 'cart_items#destroy', as: 'delete_cart_item'
  get 'cart_items/:id', to: 'cart_items#show', as: 'cart_item'
  get 'cart_items/:id/edit', to: 'cart_items#edit', as: 'edit_cart_item'

  get 'help', to: 'static_pages#help'


  resources :orders

  resources :orders do
    member do
      patch :mark_as_shipped
      patch :cancel
      put :cancel_by_user
    end
  end

  resources :contests do
    resources :contest_entries, only: [:new, :create, :show]
  end

end

app/models/vendor.rb
# == Schema Information
#
# Table name: vendors
#
#  id            :bigint           not null, primary key
#  business_name :string
#  desc          :text
#  created_at    :datetime         not null
#  updated_at    :datetime         not null
#  user_id       :bigint
#
# Indexes
#
#  index_vendors_on_id       (id) UNIQUE
#  index_vendors_on_user_id  (user_id)
#
# Foreign Keys
#
#  fk_rails_...  (user_id => users.id)
#

class Vendor < ApplicationRecord
  
  # Associations
  has_many :potions, dependent: :destroy
  belongs_to(
     :userobj,
     class_name:  'User',
     foreign_key: 'user_id',
     inverse_of:  :vendor
      )

  has_many(
     :potions,
     class_name:  'Potion',
     foreign_key: 'vendor_id',
     inverse_of:  :vendor
   )

  has_many(
    :contests,
    class_name:  'Contest',
    foreign_key: 'vendor_id',
    inverse_of:  :vendor
  )
  # Validations
  validates :business_name, presence: true
  validates :desc, presence: true

  def related_orders
    Order.joins(:potions).where(potions: { vendor_id: id }).distinct
  end

  # Add any other necessary validations or methods
end

app/controllers/vendors_controller.rb
# app/controllers/vendors_controller.rb

class VendorsController < ApplicationController
  before_action :authenticate_user!, except: [:new, :create]
  before_action :only_allow_vendors, except: [:new,:create]
  before_action :set_vendor, only: [:show, :edit, :update, :destroy]
  

  def index
    @vendors = Vendor.all
  end

  def show
  end

  def new
    if current_user && current_user.vendor
      flash[:error] = 'You\'re already a vendor.'
      redirect_to vendor_dashboard_url
    else
      @vendor = Vendor.new
    end
  end

  def create
    @vendor = current_user.build_vendor(params.require(:vendor).permit(:business_name, :desc))
    if @vendor.save
      redirect_to vendor_dashboard_url, notice: 'Vendor was successfully created.'
    else
      flash.now[:error] = 'Unable to create Vendor.'
      render :new, status: :unprocessable_entity
    end
  end

  def edit
  end

  def update
    if @vendor.update(vendor_params)
      redirect_to @vendor, notice: 'Vendor was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @vendor.destroy
    redirect_to vendors_url, notice: 'Vendor was successfully destroyed.'
  end

  def dashboard
    @vendor = current_user.vendor
    @potions = @vendor.potions
    @orders = @vendor.related_orders.order(created_at: :desc)
  end

  private

  def set_vendor
    @vendor = current_user.vendor
  end

  def vendor_params
    params.require(:vendor).permit(:name, :business_name, :contact, :email, :phone_number, :password, :password_confirmation)
  end  
  protected

  def after_sign_in_path_for(resource)
    # Check if the resource is a vendor and redirect to the dashboard
    if resource.instance_of?(Vendor)
      vendor_dashboard_path
    else
      super
    end
  end

  def only_allow_vendors
    if current_user && !current_user.vendor
      flash[:error] = 'You do not have permission to do that.'
      redirect_to root_url
    end
  end


end

app/helpers/vendors_helper.rb
module VendorsHelper
end

app/views/vendors/dashboard.html.erb
<div class="vendor-dashboard">
  <h1>Vendor Dashboard</h1>

  <h2>My Potions</h2>

  <div class="table-container">
    <table class="potions-table">
      <thead>
        <tr>
          <th>Image</th>
          <th>Name</th>
          <th>Actions</th>
        </tr>
      </thead>
      <tbody>
        <% @potions.each do |potion| %>
          <tr>
            <td class="potion-image-cell">
              <% if potion.images.attached? %>
                <%= image_tag potion.images.first, class: "potion-table-image" %>
              <% end %>
            </td>
            <td><%= link_to potion.name, nil %></td>
            <td class="actions-cell">
              <%= link_to 'Edit', edit_potion_path(potion), class: "edit-btn" %>
              <%= button_to 'Remove', potion, method: :delete, data: { confirm: 'Are you sure?' }, class: "remove-btn" %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>

  <div class="add-new-potion">
    <%= link_to 'Add New Potion', new_potion_path, class: "add-potion-btn" %>
  </div>

<h2>Orders for My Potions</h2>

<% if @orders.empty? %>
  <p>No orders yet.</p>
<% else %>
  <table>
    <thead>
      <tr>
        <th>Order ID</th>
        <th>Customer Email</th>
        <th>Total</th>
        <th>Status</th>
        <th>Actions</th>
      </tr>
    </thead>
    <tbody>
      <% @orders.each do |order| %>
        <tr>
          <td><%= order.id %></td>
          <td><%= order.user.email %></td>
          <td><%= number_to_currency(order.total) %></td>
          <td><%= order.status || "Pending" %></td>
          <td>
            <%= form_with url: mark_as_shipped_order_path(order), method: :patch do %>
  <%= submit_tag 'Mark as Shipped' %>
<% end %>
            <%= button_to 'Cancel', cancel_order_path(order), method: :patch %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% end %>
</div>

app/views/vendors/edit.html.erb
<h1>Edit Potion</h1>

<%= form_with(model: @potion, local: true, multipart: true) do |form| %>
  <% if @potion.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@potion.errors.count, "error") %> prohibited this potion from being saved:</h2>
      <ul>
        <% @potion.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :effect %>
    <%= form.text_field :effect %>
  </div>

  <!-- Include other potion fields here -->

  <div class="field">
    <%= form.label :images %>
    <%= form.file_field :images, multiple: true, accept: "image/jpeg,image/gif,image/png" %>
    <small>Allowed formats: jpg, gif, png</small>
  </div>

  <div class="actions">
    <%= form.submit "Update Potion" %>
  </div>
<% end %>

app/views/vendors/new.html.erb
<h1>Vendor Signup</h1>

<%= bootstrap_form_with model: @vendor, url: new_vendor_path, method: :post, data: { turbo: false } do |form| %>
  <%= form.text_field :business_name, label: "Name of Your Business"%>
  <%= form.text_area :desc, rows: 16, help: "Tell us about where you're located, what type of potions you brew, and how long you've been brewing.", label: "Description of Your Business"%>
  <%= form.submit class: 'btn btn-primary my-3' %>
<% end %>