config/routes.rb
Rails.application.routes.draw do
  
  
  devise_for :users
  root 'home#index'
  get 'vendor/dashboard', to: 'vendors#dashboard', as: :vendor_dashboard
  get 'potions', to: 'potions#index', as: :potions
  get 'potions/new', to: 'potions#new', as: :new_potion
  post 'potions', to: 'potions#create'
  get 'potions/:id', to: 'potions#show', as: :potion
  get 'potions/:id/edit', to: 'potions#edit', as: :edit_potion
  patch 'potions/:id', to: 'potions#update'
  put 'potions/:id', to: 'potions#update'
  delete 'potions/:id', to: 'potions#destroy'
  get 'potions/:id/vendor_show', to: 'potions#vendor_show', as: 'vendor_potion'

  get 'account', to: 'users#show'
  get 'orders', to: 'orders#index'
  
  get 'contests', to: 'contests#index', as: :contests
  post 'contests', to: 'contests#create'
  get 'contests/new', to: 'contests#new', as: :new_contest
  get 'contests/:id/edit', to: 'contests#edit', as: :edit_contest
  get 'contests/:contest_id/entries', to: 'contest_entries#index', as: :contest_entries
  get 'contests/:contest_id/entries/new', to: 'contest_entries#new', as: :new_contest_entry
  get 'contests/:contest_id/entries/:id/edit', to: 'contest_entries#edit', as: :edit_contest_entry
  patch 'contests/:contest_id/entries/:id/winner', to: 'contests#winner', as: :set_contest_winner
  delete 'contests/:contest_id/entries/:id/winner', to: 'contests#removewinner'
  get 'contests/:contest_id/entries/:id', to: 'contest_entries#show', as: :contest_entry
  patch 'contests/:contest_id/entries/:id', to: 'contest_entries#update'
  post 'contests/:contest_id/entries/:id/vote', to: 'contest_votes#create', as: :vote
  delete 'contests/:contest_id/entries/:id/vote', to: 'contest_votes#destroy'
  get 'contests/:id', to: 'contests#show', as: :contest
  patch 'contests/:id', to: 'contests#update'
  delete 'contests/:id', to: 'contests#destroy'
  get 'help', to: 'static_pages#help'

  get 'logout', to: 'sessions#destroy'


  get 'vendor/new', to: 'vendors#new', as: :new_vendor
  post 'vendor/new', to: 'vendors#create'


  #brewhub routes

  get 'brew_hub', to: 'brew_hub#index'
  get 'brew_hub/new', to: 'brew_hub#new', as: 'new_brew_hub_post'
  post 'brew_hub', to: 'brew_hub#create'
  get 'brew_hub/posts/:id', to: 'brew_hub#show', as: 'brew_hub_post'
  post 'brew_hub/posts/:id/reply', to: 'brew_hub#reply'
  get 'brew_hub/posts/:id/edit', to: 'brew_hub#edit', as: 'edit_brew_hub_post'
  patch 'brew_hub/posts/:id', to: 'brew_hub#update'
  get 'brew_hub/posts/:post_id/replies/new', to: 'brew_hub#new_reply', as: 'new_reply_brew_hub_post'
  delete 'brew_hub/posts/:id', to: 'brew_hub#destroy', as: 'delete_brew_hub_post'
  get 'brew_hub/posts/:id/view', to: 'brew_hub#view_post', as: 'view_brew_hub_post'

  get 'comment/:id', to: 'comments#edit', as: 'comment'
  patch 'comment/:id', to: 'comments#update'
  delete 'comment/:id', to: 'comments#destroy'
  post 'comment/:post_id', to: 'comments#create', as: 'new_comment'


  #cart routes

  resource :cart, only: [:show]
  post 'cart_items', to: 'cart_items#create'
  patch 'cart_items/:id', to: 'cart_items#update', as: 'update_cart_item'
  delete 'cart_items/:id', to: 'cart_items#destroy', as: 'delete_cart_item'
  get 'cart_items/:id', to: 'cart_items#show', as: 'cart_item'
  get 'cart_items/:id/edit', to: 'cart_items#edit', as: 'edit_cart_item'

  get 'help', to: 'static_pages#help'


  resources :orders

  resources :orders do
    member do
      patch :mark_as_shipped
      patch :cancel
      put :cancel_by_user
    end
  end

  resources :contests do
    resources :contest_entries, only: [:new, :create, :show]
  end

end

app/models/contest_entry.rb
# == Schema Information
#
# Table name: contest_entries
#
#  id          :bigint           not null, primary key
#  description :text
#  potion_name :string
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  contest_id  :bigint           not null
#  user_id     :bigint           not null
#
# Indexes
#
#  index_contest_entries_on_contest_id  (contest_id)
#  index_contest_entries_on_user_id     (user_id)
#
# Foreign Keys
#
#  fk_rails_...  (contest_id => contests.id)
#  fk_rails_...  (user_id => users.id)
#
class ContestEntry < ApplicationRecord
  belongs_to :user
  belongs_to :contest
  has_one_attached :image
  has_many :contest_votes
  belongs_to(
    :contest_won,
    class_name:  'Contest',
    foreign_key: 'winner_id',
    inverse_of:  :winner,
    optional: true
)
  validates :description, presence: true
  validates :potion_name, presence: true
end

app/controllers/contest_entries_controller.rb
class ContestEntriesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_contest, only: [:new, :create]

  def new
    @contest_entry = ContestEntry.new
  end

  def create
    @contest_entry = ContestEntry.new(contest_entry_params)
    @contest_entry.user = current_user
    @contest_entry.contest = @contest

    if @contest_entry.save
      redirect_to contest_path(@contest), notice: 'Your potion has been submitted to the contest.'
    else
      render :new
    end
  end

  def edit
    @contest = Contest.find(params[:contest_id])
    @contest_entry = @contest.contest_entries.find(params[:id])
    render :edit
  end

  def update
    @contest = Contest.find(params[:contest_id])
    @entry = @contest.contest_entries.find(params[:id])
    puts @entry
    if @entry.update(params.require(:contest_entry).permit(:potion_name, :description, :image))
      flash[:success] = 'Submission was successfully updated.'
      redirect_to contest_entry_url(@contest, @entry)
    else
      flash.now[:error] = 'Unable to update Submission.'
      render :edit, status: :unprocessable_entity
    end
  end

  def index
    @contest = Contest.find(params[:contest_id])
    @entries = @contest.contest_entries
    @now = DateTime.now
    render :index
  end

  def show
      @contest = Contest.find(params[:contest_id])
      @entry = @contest.contest_entries.find(params[:id])
      @vote = @entry.contest_votes.where(user_id: current_user.id)
      render :show
  end
  private

  def set_contest
    @contest = Contest.find(params[:contest_id])
  end

  def contest_entry_params
    params.require(:contest_entry).permit(:potion_id, :description, :image, :potion_name, :ingredients, :origin_city)
  end
end

app/helpers/contest_entries_helper.rb
module ContestEntriesHelper
end

app/views/contest_entries/edit.html.erb
<style>
  .contest-entry-form {
    background-color: #fff8e1;
    padding: 20px;
    border-radius: 10px;
    max-width: 600px;
    margin: auto;
  }

  .contest-entry-form label {
    font-weight: bold;
    color: #5D4037;
    display: block;
    margin-top: 10px;
  }

  .contest-entry-form textarea, .contest-entry-form select, .contest-entry-form input[type="file"] {
    width: 100%;
    padding: 8px;
    margin-top: 5px;
    border: 1px solid #DDD;
    border-radius: 4px;
  }

  .contest-entry-form input[type="submit"] {
    background-color: #7c3f2d;
    color: white;
    padding: 10px 15px;
    border: none;
    border-radius: 4px;
    cursor: pointer;
    margin-top: 20px;
    font-weight: bold;
  }

  .contest-entry-form input[type="submit"]:hover {
    background-color: darken(#7c3f2d, 10%);
  }
</style>

<% if @contest_entry.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@contest_entry.errors.count, "error") %> prohibited this contest entry from being saved:</h2>
    <ul>
      <% @contest_entry.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<div class="contest-entry-form">
  <%= form_with model: @contest_entry, url: contest_entry_path(@contest, @contest_entry), method: :patch, local: true do |form| %>
  <%= form.label :potion_name, 'Potion Name' %>
  <%= form.text_field :potion_name %>

  <%= form.label :description, 'Potion Description' %>
  <%= form.text_area :description %>

  <%= form.label :image, 'Image File' %>
  <%= form.file_field :image %>

  <%= form.submit "Submit Potion" %>
<% end %>

app/views/contest_entries/index.html.erb
<h1><%= @contest.title %></h1>
<div align="center">
    <%= link_to 'Back To Contest', contest_path(@contest), class: 'btn btn-primary', id: 'btn-style' %>
    <% if user_signed_in? and @contest.end_date > @now %>
    <%= link_to 'Submit Your Own Potion', new_contest_entry_path(@contest), class: 'btn btn-primary', id: 'btn-style' %>
    <% end %>
</div>
<div>
    <table class="table table-image" style="color: black;">
		  <tbody>
            <% @entries.each do |entry| %>
                <tr>
                    <td class="w-25">
                        <% if entry.image.attached? %>
                        <%= image_tag entry.image, class: "img-fluid img-thumbnail" %>
                        <% end %>
                    </td>
                    <td>
                    <h4><%= entry.potion_name %></h4><br>
                    <p><%= entry.description %></p>
                    <br>
                    <% @num_votes =  entry.contest_votes.length() %>
                    <div id="vote-num"><%= @num_votes %> Vote<% if @num_votes > 1 or @num_votes == 0 %>s<% end %></div>
                    <br>
                    <div class="btn-group" role="group">
                    <% if user_signed_in? and entry.contest_votes.pluck(:user_id).include? current_user.id%>
                    <%= button_to 'Remove Vote', vote_path(@contest, entry), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-primary', id: "left-btn-groupd" %>
                    <% else %>
                    <%= button_to 'Vote', vote_path(@contest, entry), method: :post, data: { confirm: 'Are you sure?' }, class: 'btn btn-primary', id: "left-btn-groupd" %>
                    <% end %>
                    <%= link_to 'View More', contest_entry_path(@contest, entry), class: 'btn btn-primary', id: 'btn-style' %>
                    <% if user_signed_in? and entry.user == current_user%>
                        <%= link_to 'Edit Entry', edit_contest_entry_path(@contest, entry), class: 'btn btn-primary', id: 'btn-style' %>
                    <% end %>
                    <% if user_signed_in? and @contest.vendor == current_user.vendor and @contest.end_date > @now%>
                        <%= button_to 'Set Winner', set_contest_winner_path(@contest, entry), method: :patch, data: { confirm: 'Are you sure?' }, class: 'btn btn-primary', id: "btn-style" %>
                    <% end %>
                    </div>
                    </td>
                </tr>
         <% end %>
		    
		  </tbody>
		</table>
</div>

app/views/contest_entries/new.html.erb
<style>
  .contest-entry-form {
    background-color: #fff8e1;
    padding: 20px;
    border-radius: 10px;
    max-width: 600px;
    margin: auto;
  }

  .contest-entry-form label {
    font-weight: bold;
    color: #5D4037;
    display: block;
    margin-top: 10px;
  }

  .contest-entry-form textarea, .contest-entry-form select, .contest-entry-form input[type="file"] {
    width: 100%;
    padding: 8px;
    margin-top: 5px;
    border: 1px solid #DDD;
    border-radius: 4px;
  }

  .contest-entry-form input[type="submit"] {
    background-color: #7c3f2d;
    color: white;
    padding: 10px 15px;
    border: none;
    border-radius: 4px;
    cursor: pointer;
    margin-top: 20px;
    font-weight: bold;
  }

  .contest-entry-form input[type="submit"]:hover {
    background-color: darken(#7c3f2d, 10%);
  }
</style>

<% if @contest_entry.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@contest_entry.errors.count, "error") %> prohibited this contest entry from being saved:</h2>
    <ul>
      <% @contest_entry.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<div class="contest-entry-form">
  <%= form_with model: @contest_entry, url: contest_contest_entries_path(@contest), local: true do |form| %>
  <%= form.label :potion_name, 'Potion Name' %>
  <%= form.text_field :potion_name %>

  <%= form.label :description, 'Potion Description' %>
  <%= form.text_area :description %>

  <%= form.label :image, 'Image File' %>
  <%= form.file_field :image %>

  <%= form.submit "Submit Potion" %>

  <%= link_to 'Back to Entries', contest_entries_path(@contest), class: 'btn btn-custom mx-1', id: "btn-group-btn" %>

<% end %>

app/views/contest_entries/show.html.erb
<style>
  .contest-entry-show {
    font-family: 'Cormorant', serif;
    color: #301934;
    background-color: #fff5e5;
    padding: 20px;
    max-width: 800px;
    margin: auto;
  }

  .contest-entry-image {
    max-width: 100%;
    height: auto;
    border-radius: 10px;
  }

  .btn-custom {
    background-color: #7c3f2d;
    color: white;
    padding: 10px 15px;
    border: none;
    border-radius: 4px;
    text-decoration: none;
    font-weight: bold;
    margin-top: 10px;
  }

  .btn-custom:hover {
    background-color: darken(#7c3f2d, 10%);
  }

  .contest-entry-image {
    max-width: 100%;
    height: auto;
    max-height: 300px; /* Adjust the maximum height as needed */
    display: block;
    margin: 20px auto; /* Center the image */
    object-fit: cover; /* Ensures the image is well-fitted */
    border-radius: 10px;
  }
  
  #btn-group-btn {
    border-top-left-radius: 5%;
    border-bottom-left-radius: 5%;
    border-top-right-radius: 5%;
    border-bottom-right-radius: 5%;
  }

</style>

<div class="contest-entry-show">
  <h1><%= @entry.potion_name %></h1>
  <% if @entry.image.attached? %>
    <%= image_tag @entry.image ,class: 'contest-entry-image'%>
  <% end %>

  <p><strong>Description:</strong> <%= @entry.description %></p>
  <% @num_votes =  @entry.contest_votes.length() %>
  <div id="vote-num"><%= @num_votes %> Vote<% if @num_votes > 1 or @num_votes == 0 %>s<% end %></div>
  <br>
  <div class="btn-group" role="group">
  <% if user_signed_in? and @entry.contest_votes.pluck(:user_id).include? current_user.id%>
  <%= button_to "Remove Vote", vote_path(@contest, @entry), method: :delete, class: "btn btn-custom mx-1", id: "btn-group-btn" %>
  <% else %>
  <%= button_to "Vote", vote_path(@contest, @entry), method: :post, class: "btn btn-custom mx-1", id: "btn-group-btn" %>
  <% end %>
  <%= link_to 'Back to Entries', contest_entries_path(@contest), class: 'btn btn-custom mx-1', id: "btn-group-btn" %>
  <%= link_to 'Or Shopping??', potions_path, class: 'btn btn-custom mx-1', id: "btn-group-btn" %>
  <% if user_signed_in? and @entry.user == current_user%>
    <%= link_to 'Edit Entry', edit_contest_entry_path(@contest, @entry), class: 'btn btn-custom mx-1', id: "btn-group-btn" %>
  <% end %>
  </div>
  <h5 class="my-5 mx-auto text-center"> Submitted to <%= @contest.title %> at <%= @entry.created_at %> </h5>
</div>